SELECT * FROM DEPARTMENT
SELECT * FROM PERSON


From the above given table perform the following queries:

--1. Find all persons with their department name & code. 
	 SELECT PERSON.PERSONNAME,
			DEPARTMENT.DEPARTMENTNAME,
			DEPARTMENT.DEPARTMENTCODE
	 FROM PERSON
	 INNER JOIN DEPARTMENT
	 ON PERSON.DEPARTMENTID=DEPARTMENT.DEPARTMENTID 


--2. Give department wise maximum & minimum salary with department name.
	SELECT DEPARTMENT.DEPARTMENTNAME,MAX(SALARY),MIN(SALARY)
	FROM PERSON
	INNER JOIN DEPARTMENT
	ON  PERSON.DEPARTMENTID=DEPARTMENT.DEPARTMENTID
	GROUP BY DEPARTMENT.DEPARTMENTNAME
		
--3. Find all departments whose total salary is exceeding 100000.
	SELECT DEPARTMENT.DEPARTMENTNAME,SUM(SALARY)
	FROM PERSON
	INNER JOIN DEPARTMENT
	ON  PERSON.DEPARTMENTID=DEPARTMENT.DEPARTMENTID
	GROUP BY DEPARTMENT.DEPARTMENTNAME
	HAVING SUM(SALARY)>100000
--4. Retrieve person name, salary & department name who belongs to Jamnagar city.
	SELECT PERSON.PERSONNAME,
		   PERSON.SALARY,
		   DEPARTMENT.DEPARTMENTNAME
	FROM PERSON
	INNER JOIN DEPARTMENT
	ON  PERSON.DEPARTMENTID=DEPARTMENT.DEPARTMENTID
	WHERE CITY='JAMNAGAR'


--5. Find all persons who does not belongs to any department.
	SELECT PERSON.PERSONNAME
	FROM PERSON
	LEFT OUTER  JOIN DEPARTMENT
	ON  PERSON.DEPARTMENTID=DEPARTMENT.DEPARTMENTID
	WHERE DEPARTMENT.DEPARTMENTID IS NULL

--6. Find department wise person counts.
	SELECT DEPARTMENT.DEPARTMENTNAME,COUNT(PERSONNAME)
	FROM PERSON
	INNER JOIN DEPARTMENT
	ON  PERSON.DEPARTMENTID=DEPARTMENT.DEPARTMENTID
	GROUP BY DEPARTMENT.DEPARTMENTNAME

--7. Find average salary of person who belongs to Ahmedabad city.
	SELECT AVG(SALARY),
		   PERSON.CITY
	FROM PERSON
	LEFT OUTER JOIN DEPARTMENT
	ON  PERSON.DEPARTMENTID=DEPARTMENT.DEPARTMENTID
	GROUP BY CITY HAVING CITY='AHMEDABAD'


--8. Produce Output Like: <PersonName> earns <Salary> from department <DepartmentName> monthly.
		--(In single column)
	SELECT PERSON.PERSONNAME + 'EARNS' + CAST(PERSON.SALARY AS VARCHAR) + 'FROM DEPARTMENT' + DEPARTMENT.DEPARTMENTNAME
	FROM PERSON
	INNER JOIN DEPARTMENT
	ON  PERSON.DEPARTMENTID=DEPARTMENT.DEPARTMENTID

--9. List all departments who have no persons.
	SELECT DEPARTMENT.DEPARTMENTNAME
	FROM PERSON
	LEFT OUTER JOIN DEPARTMENT
	ON  PERSON.DEPARTMENTID=DEPARTMENT.DEPARTMENTID
	WHERE PERSONID IS NULL

--10. Find city & department wise total, average & maximum salaries.
	--CITY WISE
	SELECT PERSON.CITY,
			SUM(SALARY),
			AVG(SALARY),
			MAX(SALARY)
	FROM PERSON
	INNER JOIN DEPARTMENT
	ON  PERSON.DEPARTMENTID=DEPARTMENT.DEPARTMENTID
	GROUP BY PERSON.CITY

	--DEPARTMENT WISE
	SELECT DEPARTMENT.DEPARTMENTNAME,
			SUM(SALARY),
			AVG(SALARY),
			MAX(SALARY)
	FROM PERSON
	INNER JOIN DEPARTMENT
	ON  PERSON.DEPARTMENTID=DEPARTMENT.DEPARTMENTID
	GROUP BY DEPARTMENT.DEPARTMENTNAME

--11. Display Unique city names.
	SELECT DISTINCT PERSON.CITY
	FROM PERSON
	LEFT OUTER JOIN DEPARTMENT
	ON  PERSON.DEPARTMENTID=DEPARTMENT.DEPARTMENTID

--12. List out department names in which more than two persons.
	SELECT DEPARTMENT.DEPARTMENTNAME
	FROM PERSON
	RIGHT OUTER JOIN DEPARTMENT
	ON  PERSON.DEPARTMENTID=DEPARTMENT.DEPARTMENTID
	GROUP BY DEPARTMENTNAME HAVING COUNT(DEPARTMENT.DEPARTMENTID)>2

--13. Combine person name’s first three characters with city name’s last three characters in single column.
	SELECT SUBSTRING(PERSON.PERSONNAME,1,3) + SUBSTRING(PERSON.CITY,LEN(PERSON.CITY)-2,LEN(PERSON.CITY))
	 FROM PERSON
	INNER JOIN DEPARTMENT
	ON  PERSON.DEPARTMENTID=DEPARTMENT.DEPARTMENTID

--14. Give 10% increment in Computer department employee’s salary.
	SELECT SALARY=SALARY+(0.1*SALARY)
	FROM PERSON
	INNER JOIN DEPARTMENT
	ON  PERSON.DEPARTMENTID=DEPARTMENT.DEPARTMENTID
	WHERE DEPARTMENTNAME='COMPUTER'
--15. Display all the person name’s who’s joining dates difference with current date is more than 365 days.
	SELECT PERSON.PERSONNAME
	FROM PERSON 
	LEFT OUTER JOIN DEPARTMENT
	ON  PERSON.DEPARTMENTID=DEPARTMENT.DEPARTMENTID
	WHERE DATEDIFF(DAY,JOININGDATE,GETDATE())>365