SELECT * FROM MST_CITY
SELECT * FROM MST_STATE

--1. Select All CityID, CityName, Pincode, CityRemarks, StateID,StateName
	CREATE PROCEDURE PR_MST_CITY_SELECTALL
	AS
	BEGIN
	SELECT CITYID,
		   CITYNAME,
		   PINCODE,
		   CITYREMARKS,
		   MST_CITY.STATE_ID,
		   STATENAME
	FROM MST_CITY
	INNER JOIN MST_STATE

	ON MST_CITY.STATE_ID = MST_STATE.STATE_ID
	END
		--EXEC PR_MST_CITY_SELECTALL

--2. Insert
	CREATE PROCEDURE PR_MAST_CITY_INSERT_1
		@CITYID				INT,
		@CITYNAME			VARCHAR(250),
		@PINCODE			VARCHAR(6),
		@STATE_ID			INT,
		@CITYREMARKS		VARCHAR(500)
	AS 
	BEGIN
	INSERT INTO MST_CITY
				(
					CITYID,		
					CITYNAME,	
					PINCODE,	
					STATE_ID,	
					CITYREMARKS
				)
		VALUES
			(
				@CITYID,		
				@CITYNAME,	
				@PINCODE,	
				@STATE_ID,	
				@CITYREMARKS
			)
	END

		--EXEC PR_MAST_CITY_INSERT_1  parameters
--3. Update
	CREATE PROCEDURE PR_MST_CITY_UPDATE
		@CITYID				INT,
		@CITYNAME			VARCHAR(250),
		@PINCODE			VARCHAR(6),
		@STATE_ID			INT,
		@CITYREMARKS		VARCHAR(500)
	AS 
	BEGIN
	UPDATE MST_CITY
		SET  		
				CITYNAME=@CITYNAME,
				PINCODE=@PINCODE,	
				STATE_ID=@STATE_ID,	
				CITYREMARKS=@CITYREMARKS
		WHERE   CITYID=@CITYID
		END

		--EXEC PR_MST_CITY_UPDATE parameters


--4. Delete
	CREATE PROCEDURE PR_MST_CITY_DELETE
		@CITYID				INT
	AS 
	BEGIN
	DELETE FROM MST_CITY
		WHERE   CITYID=@CITYID
	END

		--EXEC PR_MST_CITY_DELETE parameter


--5. SelectByPK
	CREATE PROCEDURE PR_MST_CITY_SELECTBYPK
		@CITYID				INT
	AS 
	BEGIN
	SELECT CITYID,
		   CITYNAME,
		   PINCODE,
		   CITYREMARKS,
		   STATE_ID
		  
	FROM MST_CITY

	WHERE   CITYID=@CITYID
	END

			--EXEC PR_MST_CITY_SELECTBYPK parameter


--6. SelectByPincodeStartWith360
	CREATE PROCEDURE PR_MST_CITY_STARTPINWITH360
	AS 
	BEGIN
	SELECT * FROM MST_CITY

	WHERE   PINCODE LIKE '360%'
	END
	
		--EXEC PR_MST_CITY_STARTPINWITH360


--7. SelectByCityNamePincode
	CREATE PROCEDURE PR_MST_CITY_CITYNAME_PINCODE
		@CITYNAME		VARCHAR(250),
		@PINCODE		VARCHAR(6)
	AS 
	BEGIN
	SELECT * FROM MST_CITY

	WHERE   CITYNAME=@CITYNAME	AND	PINCODE=@PINCODE
	END
		
		--EXEC PR_MST_CITY_CITYNAME_PINCODE parameters


8. SelectByCityRemarks
	CREATE PROCEDURE PR_MST_CITY_CITYREMARKS
		@CITYREMARKS  VARCHAR(500)
	AS 
	BEGIN
	SELECT * FROM MST_CITY

	WHERE   CITYREMARKS=@CITYREMARKS
	END

			--EXEC PR_MST_CITY_CITYREMARKS parameters


--9. SelectByStateID
	CREATE PROCEDURE PR_MST_CITY_STATE_ID
		@STATE_ID INT
	AS 
	BEGIN
	SELECT * FROM MST_CITY

	WHERE   STATE_ID=@STATE_ID
	END

		--EXEC PR_MST_CITY_STATE_ID parameter


--10. SelectByStateIDCityID
	CREATE PROCEDURE PR_MST_CITY_STATE_ID_CITYID
		@STATE_ID INT,
		@CITYID   INT
	AS 
	BEGIN
	SELECT * FROM MST_CITY

	WHERE   STATE_ID=@STATE_ID  AND  CITYID=@CITYID
	END

		--EXEC PR_MST_CITY_STATE_ID_CITYID parameters